apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-bot
spec:
  secretStoreRef:
    kind: SecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - secretKey: discord-token
      remoteRef:
        key: discord-bot/password
        metadataPolicy: None
        conversionStrategy: Default
        decodingStrategy: None