apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: dex
    repoURL: https://github.com/TwoDCube-Home/argocd
  destination:
    name: in-cluster
    namespace: dev
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
