apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ae2-discord-webhook
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: SecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: ae2 discord webhook/url
        metadataPolicy: None
        conversionStrategy: Default
        decodingStrategy: None
