apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pushgateway
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: SecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        web.yml: |
          basic_auth_users:
            {{ .username }}: {{ .bcrypt_hash }}
  data:
    - secretKey: username
      remoteRef:
        key: ae2 metrics password/username
        metadataPolicy: None
        conversionStrategy: Default
        decodingStrategy: None
    - secretKey: bcrypt_hash
      remoteRef:
        key: ae2 metrics password/bcrypt_hash
        metadataPolicy: None
        conversionStrategy: Default
        decodingStrategy: None
