apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pushgateway
  labels:
    app: pushgateway
spec:
  selector:
    matchLabels:
      app: pushgateway
  endpoints:
    - port: metrics
      interval: 30s
      honorLabels: true
      basicAuth:
        username:
          name: pushgateway
          key: username
        password:
          name: pushgateway
          key: password
