apiVersion: batch/v1
kind: CronJob
metadata:
  name: unifi-asn-route-updater
  labels:
    app: unifi-asn-route-updater
spec:
  schedule: "0 6 * * 1"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: unifi-asn-route-updater
        spec:
          restartPolicy: OnFailure
          containers:
            - name: unifi-asn-route-updater
              image: ghcr.io/twodcube-home/unifi-asn-route-updater:366cebef0419ea8ce27f5d47b541df15f432138e
              env:
                - name: ASNLOOKUP_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: unifi-asn-route-updater
                      key: asnlookup-api-token
                - name: UNIFI_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: unifi-asn-route-updater
                      key: unifi-api-token
