apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trek-data
  labels:
    app: trek
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trek-uploads
  labels:
    app: trek
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
