apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trek
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: SecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: trek/jwt-secret
        metadataPolicy: None
        conversionStrategy: Default
        decodingStrategy: None
    - secretKey: oidc-client-secret
      remoteRef:
        key: dex/trek-client-secret
        metadataPolicy: None
        conversionStrategy: Default
        decodingStrategy: None
