apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: SecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - secretKey: openshift-client-secret
      remoteRef:
        key: dex/openshift-client-secret
        metadataPolicy: None
        conversionStrategy: Default
        decodingStrategy: None
    - secretKey: trek-client-secret
      remoteRef:
        key: dex/trek-client-secret
        metadataPolicy: None
        conversionStrategy: Default
        decodingStrategy: None
