apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-asn-route-updater
spec:
  secretStoreRef:
    kind: SecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - secretKey: asnlookup-api-token
      remoteRef:
        key: ASN Lookup apikey/password
        metadataPolicy: None
        conversionStrategy: Default
        decodingStrategy: None
    - secretKey: unifi-api-token
      remoteRef:
        key: unifi.ui.com/apikey
        metadataPolicy: None
        conversionStrategy: Default
        decodingStrategy: None
